#!/usr/bin/env node
/**
 * Generates SEO / AEO / GEO artifacts from data/site.config.json
 * Also validates that each page has a matching HTML file.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const configPath = path.join(root, "data", "site.config.json");
const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
const today = new Date().toISOString().slice(0, 10);
const siteUrl = config.siteUrl.replace(/\/$/, "");
let errors = 0;

function abs(p) {
  if (p === "/") return `${siteUrl}/`;
  return `${siteUrl}${p.startsWith("/") ? p : `/${p}`}`;
}

function write(rel, content) {
  const out = path.join(root, rel);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, content.trimStart());
  console.log(`✓ ${rel}`);
}

function pageToFile(pagePath) {
  if (pagePath === "/") return "index.html";
  return path.join(pagePath.replace(/^\//, "").replace(/\/$/, ""), "index.html");
}

/* ---------- Validate HTML exists for every config page ---------- */
console.log("Validating pages…");
for (const page of config.pages) {
  const rel = pageToFile(page.path);
  const full = path.join(root, rel);
  if (!fs.existsSync(full)) {
    console.error(`✗ Missing HTML for ${page.path} → expected ${rel}`);
    errors += 1;
  } else {
    console.log(`  · ${page.path}`);
  }
}

/* ---------- sitemap.xml (skip noindex utility pages) ---------- */
const sitemapPages = config.pages.filter((p) => !p.noindex);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapPages
  .map(
    (page) => `  <url>
    <loc>${abs(page.path)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq || "monthly"}</changefreq>
    <priority>${Number(page.priority ?? 0.5).toFixed(1)}</priority>
  </url>`
  )
  .join("\n")}
</urlset>
`;

const robots = `# Hurfi — auto-generated from data/site.config.json
User-agent: *
Allow: /
Disallow: /thank-you/

User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Bytespider
Allow: /

Sitemap: ${siteUrl}/sitemap.xml
`;

const pageList = config.pages
  .filter((p) => !p.noindex)
  .map((p) => `- [${p.title}](${abs(p.path)}): ${p.description}`)
  .join("\n");

const faqList = (config.faqs || [])
  .map((f) => `### ${f.question}\n${f.answer}`)
  .join("\n\n");

const serviceList = (config.services || [])
  .map((s) => `- [${s.name}](${abs(s.path)})`)
  .join("\n");

const llms = `# ${config.name}
> ${config.tagline}

${config.description}

Primary audience: ${config.targetMarket}

## Services
${serviceList}

## Key pages
${pageList}

## Contact
- Email: ${config.email}
- Book a consultation: ${abs(config.primaryCTA.url)}

## FAQ
${faqList}

## Optional
- Sitemap: ${siteUrl}/sitemap.xml
- Robots: ${siteUrl}/robots.txt
`;

const humans = `/* TEAM */
Organization: ${config.name}
Contact: ${config.email}
Focus: ${config.targetMarket}

/* SITE */
Standards: HTML5, CSS3
Hosting: Netlify
Source: GitHub
Last update: ${today}
`;

const runtime = {
  generatedAt: new Date().toISOString(),
  siteUrl,
  name: config.name,
  tagline: config.tagline,
  description: config.description,
  email: config.email,
  brandColor: config.brandColor,
  ogImage: config.ogImage,
  targetMarket: config.targetMarket,
  primaryCTA: config.primaryCTA,
  nav: config.nav || [],
  pages: config.pages.map(({ path: p, title, description, type, geo, noindex }) => ({
    path: p,
    title,
    description,
    type,
    geo: geo || null,
    noindex: !!noindex,
  })),
  faqs: config.faqs || [],
  services: config.services || [],
};

const siteDataJs = `/* Auto-generated by scripts/generate-seo.mjs — do not edit by hand */
window.HURFI_SITE = ${JSON.stringify(runtime, null, 2)};
`;

const orgSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: config.name,
  legalName: config.legalName || config.name,
  url: siteUrl,
  email: config.email,
  description: config.description,
  slogan: config.tagline,
  logo: `${siteUrl}/favicon.svg`,
  areaServed: [
    { "@type": "Country", name: "China" },
    { "@type": "Place", name: "Global" },
  ],
  knowsAbout: [
    "Chinese manufacturers digital marketing",
    "B2B website development",
    "SEO for Chinese suppliers",
    "Social media management for B2B",
  ],
  sameAs: config.sameAs || [],
  contactPoint: {
    "@type": "ContactPoint",
    email: config.email,
    contactType: "sales",
    availableLanguage: ["English", "Chinese"],
  },
};

const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: config.name,
  url: siteUrl,
  description: config.description,
  inLanguage: config.locale || "en",
  publisher: { "@type": "Organization", name: config.name, url: siteUrl },
  potentialAction: {
    "@type": "ReserveAction",
    target: abs(config.primaryCTA.url),
    name: config.primaryCTA.label,
  },
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: (config.faqs || []).map((f) => ({
    "@type": "Question",
    name: f.question,
    acceptedAnswer: { "@type": "Answer", text: f.answer },
  })),
};

const professionalServiceSchema = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: config.name,
  url: siteUrl,
  description: config.description,
  areaServed: { "@type": "Country", name: "China" },
  serviceType: (config.services || []).map((s) => s.name),
  audience: {
    "@type": "BusinessAudience",
    audienceType: config.targetMarket,
  },
};

const schemaJs = `/* Auto-generated JSON-LD bundles for SEO / AEO / GEO */
window.HURFI_SCHEMA = {
  organization: ${JSON.stringify(orgSchema, null, 2)},
  website: ${JSON.stringify(websiteSchema, null, 2)},
  faqPage: ${JSON.stringify(faqSchema, null, 2)},
  professionalService: ${JSON.stringify(professionalServiceSchema, null, 2)}
};
`;

const aiTxt = `# AI / answer engines
Site: ${siteUrl}
llms: ${siteUrl}/llms.txt
sitemap: ${siteUrl}/sitemap.xml
contact: ${config.email}
audience: ${config.targetMarket}
`;

/* Inject static JSON-LD into index.html between markers (works without JS) */
const indexPath = path.join(root, "index.html");
if (fs.existsSync(indexPath)) {
  let indexHtml = fs.readFileSync(indexPath, "utf8");
  const block = `<!-- SEO:JSONLD:START -->
  <script type="application/ld+json">${JSON.stringify(orgSchema)}</script>
  <script type="application/ld+json">${JSON.stringify(websiteSchema)}</script>
  <script type="application/ld+json">${JSON.stringify(faqSchema)}</script>
  <script type="application/ld+json">${JSON.stringify(professionalServiceSchema)}</script>
  <!-- SEO:JSONLD:END -->`;

  if (indexHtml.includes("<!-- SEO:JSONLD:START -->")) {
    indexHtml = indexHtml.replace(
      /<!-- SEO:JSONLD:START -->[\s\S]*?<!-- SEO:JSONLD:END -->/,
      block
    );
  } else {
    indexHtml = indexHtml.replace("</head>", `  ${block}\n</head>`);
  }
  fs.writeFileSync(indexPath, indexHtml);
  console.log("✓ index.html JSON-LD markers updated");
}

write("sitemap.xml", sitemap + "\n");
write("robots.txt", robots);
write("llms.txt", llms + "\n");
write("ai.txt", aiTxt);
write("humans.txt", humans);
write("assets/js/site-data.js", siteDataJs);
write("assets/js/schema-data.js", schemaJs);

if (errors) {
  console.error(`\nBuild finished with ${errors} missing page(s). Fix before deploy.`);
  process.exit(1);
}

console.log(`\nSEO artifacts generated for ${config.pages.length} pages (${today}).`);
